# -*- coding: utf-8 -*-
from . import test_ck_shop_phase3_compose
from . import test_ck_shop_phase3_hooks
from . import test_ck_product_phase4_compose
from . import test_ck_product_phase4_hooks
from . import test_ck_pro_phase5_compose
from . import test_ck_pro_phase5_hooks
from . import test_ck_phase6_compose
from . import test_ck_phase6_hooks
from . import test_ck_phase7_compose
from . import test_ck_phase7_hooks
from . import test_ck_phase8_compose
from . import test_ck_phase8_hooks
from . import test_ck_phase9_compose
from . import test_ck_phase9_hooks
from . import test_ck_mentions_legales_compose
from . import test_ck_home_lot1_compose
from . import test_ck_home_lot1_hooks
from . import test_ck_home_lot2_compose
from . import test_ck_home_lot2_hooks
from . import test_ck_home_lot3_compose
from . import test_ck_home_lot3_hooks
from . import test_ck_home_lot4_compose
from . import test_ck_home_lot4_hooks
from . import test_ck_home_lot5_compose
from . import test_ck_home_lot5_hooks
from . import test_ck_home_section2_trust_bar_compose
from . import test_ck_home_section2_trust_bar_hooks
from . import test_ck_home_section3_featured_compose
from . import test_ck_home_section3_featured_hooks
from . import test_ck_catalog_manioc_variants
from . import test_ck_home_section3_curation
from . import test_ck_home_section4_univers
from . import test_ck_home_section4_univers_compose
