# -*- coding: utf-8 -*-
from . import test_ck_cms_seed_guard
from . import test_ck_featured_card_markers
from . import test_ck_featured_propagation
from . import test_ck_shop_phase3_compose
from . import test_ck_shop_phase3_hooks
from . import test_ck_shop_product_card
from . import test_ck_product_phase4_compose
from . import test_ck_product_phase4_hooks
from . import test_ck_pro_phase5_compose
from . import test_ck_pro_phase5_hooks
from . import test_ck_phase6_compose
from . import test_ck_phase6_hooks
from . import test_ck_phase7_compose
from . import test_ck_phase7_hooks
from . import test_ck_phase8_compose
from . import test_ck_phase8_hooks
from . import test_ck_phase9_compose
from . import test_ck_phase9_hooks
from . import test_ck_mentions_legales_compose
from . import test_ck_nav_sync
from . import test_ck_nav_communaute_regression
from . import test_ck_nav_axe_b_labels
from . import test_ck_home_lot1_compose
from . import test_ck_home_lot1_hooks
from . import test_ck_home_lot2_compose
from . import test_ck_home_lot2_hooks
from . import test_ck_home_lot3_compose
from . import test_ck_home_lot3_hooks
from . import test_ck_home_lot4_compose
from . import test_ck_home_lot4_hooks
from . import test_ck_home_lot5_compose
from . import test_ck_home_lot5_hooks
from . import test_ck_home_section2_trust_bar_compose
from . import test_ck_home_section2_trust_bar_hooks
from . import test_ck_home_section3_featured_compose
from . import test_ck_home_section3_featured_hooks
from . import test_ck_catalog_manioc_variants
from . import test_ck_axe_c_bo_sync
from . import test_ck_moa2_bo_sync
from . import test_ck_product_sales_tab_bo
from . import test_ck_product_page_lot2
from . import test_ck_product_page_lot2_front
from . import test_ck_product_page_tabs
from . import test_ck_product_page_note08
from . import test_ck_product_page_note08_recette
from . import test_ck_recette_u3
from . import test_ck_product_origin_unification
from . import test_ck_home_section3_curation
from . import test_ck_home_section3_featured_field
from . import test_ck_home_section3_featured_pricelist
from . import test_ck_home_section4_univers
from . import test_ck_home_section4_univers_compose
from . import test_ck_contactus_a11y_rgpd
from . import test_ck_footer_legal_links
from . import test_ck_shop_category_tiles
from . import test_ck_shop_rebound
from . import test_ck_shop_filter_drawer
from . import test_ck_shop_sparse_grid
from . import test_ck_shop_toolbar
from . import test_ck_shop_universe_banner
