# -*- coding: utf-8 -*-
from . import test_marketone_lot2_1_design
from . import test_marketone_lot2_home
from . import test_marketone_lot3_shop
from . import test_marketone_lot4_product
from . import test_marketone_lot5_cart_checkout
from . import test_marketone_lot6_1_featured
from . import test_marketone_lot6_2_origin
from . import test_marketone_lot6_3a_promo
from . import test_marketone_lot6_3b_pack
from . import test_marketone_seo_portes_shop
from . import test_marketone_shop_sidebar_categories
from . import test_marketone_collection_lot_a
from . import test_marketone_shop_sidebar_collections
from . import test_marketone_shop_filter_state
from . import test_marketone_shop_regression
from . import test_marketone_shop_wishlist
from . import test_marketone_shop_in_place
from . import test_marketone_culture_v1
from . import test_marketone_culture_v2
from . import test_marketone_origin_reunion_dedup
from . import test_marketone_shop_sidebar_ux2
from . import test_marketone_shop_tile_image
from . import test_marketone_product_form_bo
from . import test_marketone_smoke
