# -*- coding: utf-8 -*-
{
    "name": "C-Kreyol Marketone",
    "version": "19.0.15.14.1",
    "category": "Website/Website",
    "summary": "Canal e-commerce C-Kreyol — presentation et orientation (Marketone).",
    "author": "Dorevia",
    "license": "LGPL-3",
    "depends": [
        "portal",
        "website",
        "website_sale",
        "website_sale_wishlist",
    ],
    "data": [
        "data/marketone_config_parameter.xml",
        "data/marketone_header_fixed.xml",
        "data/marketone_shop_tile_config.xml",
        "data/marketone_website_shop_grid.xml",
        "data/marketone_website_shop_sidebar.xml",
        "data/marketone_product_attribute_origin.xml",
        "data/marketone_product_attribute_origin_label.xml",
        "security/ir.model.access.csv",
        "views/layout/website_layout.xml",
        "views/layout/header.xml",
        "views/layout/footer.xml",
        "views/pages/home.xml",
        "views/pages/shop.xml",
        "views/pages/shop_sidebar_categories.xml",
        "views/pages/shop_sidebar_collections.xml",
        "views/pages/shop_sidebar_origin_label.xml",
        "views/pages/shop_clear_filters.xml",
        "views/pages/shop_filter_state.xml",
        "views/pages/shop_grid_title.xml",
        "views/pages/shop_empty_state.xml",
        "views/pages/shop_wishlist.xml",
        "views/pages/shop_sidebar_ux2.xml",
        "views/marketone_shop_origin_views.xml",
        "views/marketone_shop_collection_views.xml",
        "views/product_template_shop_tile_views.xml",
        "views/pages/shop_product_tile_image.xml",
        "views/pages/shop_product_tile_conversion.xml",
        "views/pages/shop_product_preview.xml",
        "views/pages/shop_featured.xml",
        "views/pages/shop_origin.xml",
        "views/pages/product.xml",
        "views/pages/product_origin.xml",
        "views/pages/culture_territory.xml",
        "views/pages/cart.xml",
        "views/pages/checkout.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "dorevia_ckreyol_marketone/static/src/scss/_tokens_colors.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_tokens_typography.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_tokens_spacing.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_tokens_radius.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_layout.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_buttons.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_header.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_footer.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_home.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_shop.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_shop_grid_header.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_shop_sidebar.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_shop_filter_state.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_shop_product_cards.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_shop_product_preview.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_shop_wishlist.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_shop_featured.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_shop_origin.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_culture.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_product_origin.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_product.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_cart.scss",
            "dorevia_ckreyol_marketone/static/src/scss/_checkout.scss",
            "dorevia_ckreyol_marketone/static/src/scss/marketone.scss",
            "dorevia_ckreyol_marketone/static/src/js/marketone_shop_sidebar.js",
            "dorevia_ckreyol_marketone/static/src/interactions/**/*",
        ],
        "web.assets_frontend_minimal": [
            "dorevia_ckreyol_marketone/static/src/js/marketone_fixed_header.js",
        ],
    },
    "installable": True,
    "application": False,
    "post_init_hook": "post_init_hook",
}
